# Generated by Django 3.1.1 on 2020-09-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='username',
            field=models.CharField(default='@SazuuDog', help_text='Username on this service.', max_length=300),
        ),
    ]
