# Generated by Django 3.1.1 on 2020-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20200925_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('129430', 'No Logo'), ('128248', 'Instagram'), ('127925', 'TikTok'), ('128250', 'Twitch'), ('128036', 'Twitter')], default='129430', help_text='Emoji logo for this service.', max_length=30),
        ),
    ]
