# Generated by Django 3.1.1 on 2020-09-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20200927_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Used to order the links'),
        ),
    ]
